CREATE TABLE dbo.Users
	(
	UserId int NOT NULL IDENTITY (1, 1),
	Email nvarchar(128) NOT NULL,
	HashedPassword nvarchar(256) NOT NULL,
	FirstName nvarchar(64) NOT NULL,
	LastName nvarchar(64) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Users ADD CONSTRAINT
	PK_Users PRIMARY KEY CLUSTERED 
	(
	UserId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Users SET (LOCK_ESCALATION = TABLE)