BEGIN TRANSACTION

CREATE TABLE dbo.Localizations
	(
	Id int NOT NULL IDENTITY (1, 1),
	ControlName nvarchar(512) NOT NULL,
	Page nvarchar(512) NOT NULL,
	English nvarchar(MAX) NOT NULL,
	Thai nvarchar(MAX) NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]

ALTER TABLE dbo.Localizations ADD CONSTRAINT
	PK_Localizations PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


ALTER TABLE dbo.Localizations SET (LOCK_ESCALATION = TABLE)

COMMIT